### ISSUE TITLE
Argv duplication?

### ISSUE THREAD

**Issue by Sigmanificient** [viperML/noshell#1]
Is there any reason behind duplicating `argv`  into `new_argv`?

**Comment by viperML** [comment]
Duplicating the args passed to the original shell but changing argv[0]

**Comment by Sigmanificient** [comment]
Couldn't just `argv[0]`be changed, since it is no used anywhere after due to `execvp`
It would avoid memory allocation and the usage of a VLA.

**Comment by viperML** [comment]
perhaps
