### ISSUE TITLE
Issues with zeroth argument going into shell

### ISSUE THREAD

**Issue by Rutherther** [viperML/noshell#4]
# Issue
According to Bash documentation, and I bet it's also somewhere in login documentation, but I did not find it, there are two ways to indicate a login shell. Either the first character of zeroth argument is `'-'`, or with `--login` flag.
See https://www.gnu.org/software/bash/manual/html_node/Invoking-Bash.html
> A login shell is one whose first character of argument zero is ‘-’, or one invoked with the --login option.

For example, when I turn on logging of all of the argument going into noshell, and start it in a TTY, I get only one argument, and it's `-noshell`. No other argument like `-l` or `--login` are supplied.

Noshell currently passes `/home/{user}/.config/shell` as the zeroth argument to all of the shells. This means it cannot act as a login shell on systems where the first option with prepending `-` is used.

Additionally, it does not seem to properly work with shells such as `zsh`, because they try to emulate other shells like sh or bash when the zeroth argument is matched against some patterns. Specifically, `zsh` looks if the first character of zeroth argument's file name is `s`, and if it is, it decides to emulate `sh`. 
This can be seen here https://github.com/zsh-users/zsh/blob/efb7a962073988b4212820b02017980f5ec83f38/Src/init.c#L260

# Proposed solution
Instead of passing `/home/{user}/.config/shell` as a first argument, pass in value from `readlink` of the shell file when the shell file is a link. Additionally, if the first character of zeroth argument is `-`, pass that through as the first character.

The idea behind this is to act like there is no middle man like `noshell` - to imagine that it was `login` calling the program, and not `noshell`. In that case passwd would contain something like `/run/current-system/sw/zsh`, and it would be called with `-/run/current/system/sw/zsh` as first argument.

**Comment by viperML** [comment]
why not call with argv0 `-/home/user/.config/shell` ?

**Comment by Rutherther** [comment]
I thought that was explained. Zsh assumes sh emulation when first character of $0 is `s`

**Comment by viperML** [comment]
Then we could just passthru argv0 unmodified

**Comment by Rutherther** [comment]
Yes, that's one possibility, but it seems to me to be more of a workaround. I really think the best is to try to make it behave as much as possible like if the symlinked file was inside of passwd file to prevent further issues like other shells assuming emulation of something based on the argv0

I've made a demonstration for you to make the various  behaviors clearer, in a VM. There are a couple of users, all with password `vm`. User new and old are the main ones. `new` uses the version with changes I made in #5. `old` uses the current upstream version. Additionally, both versions are patched to show arguments going into noshell, and the new one argument going to the execvp as well. See https://github.com/Rutherther/noshell-vm-argv0-demonstration

Additionally, there are new-bash-emulation and new-sh-emulation that show that if your $0 is something specially handled by zsh, you can get emulation by mistake.

**Comment by viperML** [comment]
Are there any counterpoints to the argv0 passthru?

**Comment by Rutherther** [comment]
I don't know of a shell that would assume `n` or `noshell` means to use different behavior. Zsh uses c, k, s, b (https://github.com/zsh-users/zsh/blob/efb7a962073988b4212820b02017980f5ec83f38/Src/options.c#L538). But maybe there is other shell that uses this and will have issues.

**Comment by Rutherther** [comment]
I think this boils down to what noshell's goal is. I thought it was something like this: emulate `/etc/passwd` shell behavior, with possibility for users to change their (login) shell, without root rights, without changing `/etc/passwd`.

If this is the goal, I think it would make sense to make the behavior so that what the shell links points to is treated as if it was in `/etc/passwd`. Then it seems inappropriate to me to pass through `-noshell`, as the behavior would be different when the symlinked file would be actually in `/etc/passwd`.

On the other hand, if this is not the exact goal, then it's probably fine. Worst case scenario the user does not have to use `shell` file as a symlink, but can make it a script or a program of their own that will just execute their shell with correct argv0. Maybe on that note it could be useful to also provide other script or program in this repository that would do this exactly - change the argv0 to whatever the user deems appropriate and call the shell binary.

**Comment by viperML** [comment]
> I don't know of a shell that would assume `n` or `noshell` means to use different behavior. Zsh uses c, k, s, b (https://github.com/zsh-users/zsh/blob/efb7a962073988b4212820b02017980f5ec83f38/Src/options.c#L538). But maybe there is other shell that uses this and will have issues.

after seeing the argv0 hacks in the shells, you have convinced me to not go the `-noshell` as argv0 route

**Comment by viperML** [comment]
I think another solution would be:

Stat ~/.config/shell. If it is:
- Regular file -> set argv0 to `shell` or `-shell`
- Symlink -> do a `realpath` to unfold all the symlink chains, as use the basename or -basename as the argv0

**Comment by viperML** [comment]
I believe that is the intent of #5 but I haven't looked into it deeply

**Comment by Rutherther** [comment]
> I believe that is the intent of #5 but I haven't looked into it deeply

Yes, that is the intent, with one difference, it uses read link instead of realpath. The reason behind that is to respect other symlinks argv0. Imagine someone has /bin/bash - > /bin/zsh. If /bin/bash is put into passwd, it should be called with bash as argv0. Real path would mean calling with zsh argv0.

(I am omitting full paths in my messages since they dont seem that important at least in zsh. The real solution uses full paths, not just name of file)
